### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by i001962** [yodorada/gatsby-source-yodorada-webservice#1]
More of a question than a bug report I think. Does this plugin support V2?

I'm trying to access this api
````
{
    resolve: 'gatsby-source-yodorada-webservice',
    options: {
      host: `https://api.iextrading.com/1.0/ref-data/`, // the absolute path to your RESTful API
      endpoints: [`symbols`], // the endpoints from where you want to fetch
      user: ``, // the login username
      password: ``, // the login password
      apiKey: ``, // the unique api key
      conflictPrefix: `yoId`, // rename conflicting fields, will be camelCased (eg: yoId)
      options: {} // additional options (not yet implemented)
    }
 ````
There is no api key or userid required. at Gatsby Develop I'm getting this error:
-source and transform nodesYodorada Webservice Error: TypeError: Cannot read property 'map' of undefined

Any suggestions would be appreciated.
UPDATE
It's no an authentication issue. 
Looks like there may be an issue here
https://github.com/yodorada/gatsby-source-yodorada-webservice/blob/ff0ffd93d36da9501b176bd0b01280fb6fe1dfff/gatsby-node.js#L35
as res.data is undefined. If I change it to res.map I can see the nodes that are to be created but it fails with different error.
````
 Error: Could not find function loadNodeContent for plugin gatsby-source-yodora  da-webservice
`````

**Comment by i001962** [comment]
In the end I used another plugin as the loadNodeContent error was a bridge too far for me today.
https://github.com/abonventre/gatsby-source-thirdparty

**Comment by yodorada** [comment]
Hi, I am glad you found a solution.  
I created this plugin to use exclusively with the RESTful API, that I once coded, see: [PHP-Webservice-REST-API](https://github.com/yodorada/PHP-Webservice-REST-API).  
So it is not a surprise, it did not work out as you wanted.  
You could have formed your response json a little differently though, just to match the expected array mapping where your error occured:  
```json
data: [{"key1":"value1","key2":"value2"},{"key1":"value1","key2":"value2"},{}]
```
Should have worked like that I guess.  
All best and sending good coding vibes!
